//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI {
    
    public partial class AccessApproval {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lblRegionTitle;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAccessApproval;
        protected System.Web.UI.WebControls.Panel ExceptionPanel;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.HtmlControls.HtmlTable Table1;
        protected System.Web.UI.WebControls.Label lblTitle;
        protected System.Web.UI.WebControls.Label lblTeamName;
        protected System.Web.UI.WebControls.TextBox txtUserAcc;
        protected System.Web.UI.WebControls.TextBox txtRegion;
        protected System.Web.UI.WebControls.DropDownList ddlRoles;
        protected System.Web.UI.WebControls.TextBox txtPurpose;
        protected System.Web.UI.WebControls.Label lblMessage;
        protected System.Web.UI.WebControls.Button cmdSubmit;
        protected System.Web.UI.WebControls.Button cmdReset;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSiteMaintenance;
        protected System.Web.UI.HtmlControls.HtmlTable Table2;
        protected System.Web.UI.WebControls.Label lblSiteMaintenanceMessage;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidTeamOwner;
    }
}
