//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using Shell.SharePoint.DREAM.CustomSOAPHeader;
using Shell.SharePoint.DREAM.Utilities;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
 
namespace Shell.SharePoint.DREAM.Controller.QueryBuilder
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "QueryManagerServiceSoapBinding", Namespace = "http://query.services.dream.shell.com.report/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getQueryResults))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getQueryResultsResponse))]
    public partial class QueryManagerService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback getQueryResultsOperationCompleted;

        /// <remarks/>
        public QueryManagerService()
        {
            this.Url = PortalConfiguration.GetInstance().GetKey("Query Service URL");
        }

        /// <remarks/>
        public event getQueryResultsCompletedEventHandler getQueryResultsCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://query.services.dream.shell.com.report/getQueryResults",
         RequestNamespace = "http://query.services.dream.shell.com.report/",
         ResponseNamespace = "http://query.services.dream.shell.com.report/",
          Use = System.Web.Services.Description.SoapBindingUse.Literal,
          ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [DreamExtension(Name = "getQueryResults", Priority = 1)]
        public object getQueryResults([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] object requestinfo, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] int maxrecords, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string sortColumn, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] int sortOrder)
        {
            object[] results = this.Invoke("getQueryResults", new object[] {
                    requestinfo,
                    maxrecords,
                    sortColumn,
                    sortOrder});
            return ((object)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetQueryResults(object requestinfo, int maxrecords, string sortColumn, int sortOrder, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getQueryResults", new object[] {
                    requestinfo,
                    maxrecords,
                    sortColumn,
                    sortOrder}, callback, asyncState);
        }

        /// <remarks/>
        public object EndgetQueryResults(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((object)(results[0]));
        }

        /// <remarks/>
        public void getQueryResultsAsync(object requestinfo, int maxrecords, string sortColumn, int sortOrder)
        {
            this.getQueryResultsAsync(requestinfo, maxrecords, sortColumn, sortOrder, null);
        }

        /// <remarks/>
        public void getQueryResultsAsync(object requestinfo, int maxrecords, string sortColumn, int sortOrder, object userState)
        {
            if ((this.getQueryResultsOperationCompleted == null))
            {
                this.getQueryResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetQueryResultsOperationCompleted);
            }
            this.InvokeAsync("getQueryResults", new object[] {
                    requestinfo,
                    maxrecords,
                    sortColumn,
                    sortOrder}, this.getQueryResultsOperationCompleted, userState);
        }

        private void OngetQueryResultsOperationCompleted(object arg)
        {
            if ((this.getQueryResultsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getQueryResultsCompleted(this, new getQueryResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://query.services.dream.shell.com.report/")]
    public partial class getQueryResults
    {

        private object requestinfoField;

        private int maxrecordsField;

        private string sortColumnField;

        private int sortOrderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object requestinfo
        {
            get
            {
                return this.requestinfoField;
            }
            set
            {
                this.requestinfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int maxrecords
        {
            get
            {
                return this.maxrecordsField;
            }
            set
            {
                this.maxrecordsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sortColumn
        {
            get
            {
                return this.sortColumnField;
            }
            set
            {
                this.sortColumnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sortOrder
        {
            get
            {
                return this.sortOrderField;
            }
            set
            {
                this.sortOrderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://query.services.dream.shell.com.report/")]
    public partial class getQueryResultsResponse
    {

        private object returnField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void getQueryResultsCompletedEventHandler(object sender, getQueryResultsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getQueryResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getQueryResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public object Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
}