//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using Shell.SharePoint.DREAM.CustomSOAPHeader;
using Shell.SharePoint.DREAM.Utilities;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "ResourceManagerServiceSoapBinding", Namespace = "http://services.dream.shell.com.resource/")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getResourceStatusResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getResourceStatus))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getFunctionalityUsageResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getFunctionalityUsage))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getSearchNamesResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getSearchNames))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getUserNamesResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getUserNames))]
public partial class ResourceServiceProxy : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback getUserNamesOperationCompleted;

    private System.Threading.SendOrPostCallback getSearchNamesOperationCompleted;

    private System.Threading.SendOrPostCallback getFunctionalityUsageOperationCompleted;

    private System.Threading.SendOrPostCallback getResourceStatusOperationCompleted;

    /// <remarks/>
    public ResourceServiceProxy()
    {
        this.Url = PortalConfiguration.GetInstance().GetKey("ResourceServiceURL");
    }

    /// <remarks/>
    public event getUserNamesCompletedEventHandler getUserNamesCompleted;

    /// <remarks/>
    public event getSearchNamesCompletedEventHandler getSearchNamesCompleted;

    /// <remarks/>
    public event getFunctionalityUsageCompletedEventHandler getFunctionalityUsageCompleted;

    /// <remarks/>
    public event getResourceStatusCompletedEventHandler getResourceStatusCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://services.dream.shell.com.resource/", ResponseNamespace = "http://services.dream.shell.com.resource/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [DreamExtension(Name = "getUserNames", Priority = 1)]
    public object getUserNames([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] object requestinfo, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] int maxrecords, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string sortColumn, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] int sortOrder)
    {
        object[] results = this.Invoke("getUserNames", new object[] {
                    requestinfo,
                    maxrecords,
                    sortColumn,
                    sortOrder});
        return ((object)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BegingetUserNames(object requestinfo, int maxrecords, string sortColumn, int sortOrder, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("getUserNames", new object[] {
                    requestinfo,
                    maxrecords,
                    sortColumn,
                    sortOrder}, callback, asyncState);
    }

    /// <remarks/>
    public object EndgetUserNames(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((object)(results[0]));
    }

    /// <remarks/>
    public void getUserNamesAsync(object requestinfo, int maxrecords, string sortColumn, int sortOrder)
    {
        this.getUserNamesAsync(requestinfo, maxrecords, sortColumn, sortOrder, null);
    }

    /// <remarks/>
    public void getUserNamesAsync(object requestinfo, int maxrecords, string sortColumn, int sortOrder, object userState)
    {
        if ((this.getUserNamesOperationCompleted == null))
        {
            this.getUserNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserNamesOperationCompleted);
        }
        this.InvokeAsync("getUserNames", new object[] {
                    requestinfo,
                    maxrecords,
                    sortColumn,
                    sortOrder}, this.getUserNamesOperationCompleted, userState);
    }

    private void OngetUserNamesOperationCompleted(object arg)
    {
        if ((this.getUserNamesCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getUserNamesCompleted(this, new getUserNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://services.dream.shell.com.resource/", ResponseNamespace = "http://services.dream.shell.com.resource/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [DreamExtension(Name = "getSearchNames", Priority = 1)]
    public object getSearchNames()
    {
        object[] results = this.Invoke("getSearchNames", new object[0]);
        return ((object)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BegingetSearchNames(System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("getSearchNames", new object[0], callback, asyncState);
    }

    /// <remarks/>
    public object EndgetSearchNames(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((object)(results[0]));
    }

    /// <remarks/>
    public void getSearchNamesAsync()
    {
        this.getSearchNamesAsync(null);
    }

    /// <remarks/>
    public void getSearchNamesAsync(object userState)
    {
        if ((this.getSearchNamesOperationCompleted == null))
        {
            this.getSearchNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSearchNamesOperationCompleted);
        }
        this.InvokeAsync("getSearchNames", new object[0], this.getSearchNamesOperationCompleted, userState);
    }

    private void OngetSearchNamesOperationCompleted(object arg)
    {
        if ((this.getSearchNamesCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getSearchNamesCompleted(this, new getSearchNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://services.dream.shell.com.resource/", ResponseNamespace = "http://services.dream.shell.com.resource/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [DreamExtension(Name = "getFunctionalityUsage", Priority = 1)]
    public object getFunctionalityUsage([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] object requestinfo, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] int maxrecords, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string sortColumn, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] int sortOrder)
    {
        object[] results = this.Invoke("getFunctionalityUsage", new object[] {
                    requestinfo,
                    maxrecords,
                    sortColumn,
                    sortOrder});
        return ((object)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BegingetFunctionalityUsage(object requestinfo, int maxrecords, string sortColumn, int sortOrder, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("getFunctionalityUsage", new object[] {
                    requestinfo,
                    maxrecords,
                    sortColumn,
                    sortOrder}, callback, asyncState);
    }

    /// <remarks/>
    public object EndgetFunctionalityUsage(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((object)(results[0]));
    }

    /// <remarks/>
    public void getFunctionalityUsageAsync(object requestinfo, int maxrecords, string sortColumn, int sortOrder)
    {
        this.getFunctionalityUsageAsync(requestinfo, maxrecords, sortColumn, sortOrder, null);
    }

    /// <remarks/>
    public void getFunctionalityUsageAsync(object requestinfo, int maxrecords, string sortColumn, int sortOrder, object userState)
    {
        if ((this.getFunctionalityUsageOperationCompleted == null))
        {
            this.getFunctionalityUsageOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFunctionalityUsageOperationCompleted);
        }
        this.InvokeAsync("getFunctionalityUsage", new object[] {
                    requestinfo,
                    maxrecords,
                    sortColumn,
                    sortOrder}, this.getFunctionalityUsageOperationCompleted, userState);
    }

    private void OngetFunctionalityUsageOperationCompleted(object arg)
    {
        if ((this.getFunctionalityUsageCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getFunctionalityUsageCompleted(this, new getFunctionalityUsageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://services.dream.shell.com.resource/", ResponseNamespace = "http://services.dream.shell.com.resource/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [DreamExtension(Name = "getResourceStatus", Priority = 1)]
    public object getResourceStatus()
    {
        object[] results = this.Invoke("getResourceStatus", new object[0]);
        return ((object)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BegingetResourceStatus(System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("getResourceStatus", new object[0], callback, asyncState);
    }

    /// <remarks/>
    public object EndgetResourceStatus(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((object)(results[0]));
    }

    /// <remarks/>
    public void getResourceStatusAsync()
    {
        this.getResourceStatusAsync(null);
    }

    /// <remarks/>
    public void getResourceStatusAsync(object userState)
    {
        if ((this.getResourceStatusOperationCompleted == null))
        {
            this.getResourceStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetResourceStatusOperationCompleted);
        }
        this.InvokeAsync("getResourceStatus", new object[0], this.getResourceStatusOperationCompleted, userState);
    }

    private void OngetResourceStatusOperationCompleted(object arg)
    {
        if ((this.getResourceStatusCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getResourceStatusCompleted(this, new getResourceStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.dream.shell.com.resource/")]
public partial class getResourceStatusResponse
{

    private object returnField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.dream.shell.com.resource/")]
public partial class getResourceStatus
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.dream.shell.com.resource/")]
public partial class getFunctionalityUsageResponse
{

    private object returnField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.dream.shell.com.resource/")]
public partial class getFunctionalityUsage
{

    private object requestinfoField;

    private int maxrecordsField;

    private string sortColumnField;

    private int sortOrderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object requestinfo
    {
        get
        {
            return this.requestinfoField;
        }
        set
        {
            this.requestinfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int maxrecords
    {
        get
        {
            return this.maxrecordsField;
        }
        set
        {
            this.maxrecordsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sortColumn
    {
        get
        {
            return this.sortColumnField;
        }
        set
        {
            this.sortColumnField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int sortOrder
    {
        get
        {
            return this.sortOrderField;
        }
        set
        {
            this.sortOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.dream.shell.com.resource/")]
public partial class getSearchNamesResponse
{

    private object returnField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.dream.shell.com.resource/")]
public partial class getSearchNames
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.dream.shell.com.resource/")]
public partial class getUserNamesResponse
{

    private object returnField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.dream.shell.com.resource/")]
public partial class getUserNames
{

    private object requestinfoField;

    private int maxrecordsField;

    private string sortColumnField;

    private int sortOrderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object requestinfo
    {
        get
        {
            return this.requestinfoField;
        }
        set
        {
            this.requestinfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int maxrecords
    {
        get
        {
            return this.maxrecordsField;
        }
        set
        {
            this.maxrecordsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sortColumn
    {
        get
        {
            return this.sortColumnField;
        }
        set
        {
            this.sortColumnField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int sortOrder
    {
        get
        {
            return this.sortOrderField;
        }
        set
        {
            this.sortOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getUserNamesCompletedEventHandler(object sender, getUserNamesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getUserNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal getUserNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
        :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public object Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((object)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getSearchNamesCompletedEventHandler(object sender, getSearchNamesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getSearchNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal getSearchNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
        :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public object Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((object)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getFunctionalityUsageCompletedEventHandler(object sender, getFunctionalityUsageCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getFunctionalityUsageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal getFunctionalityUsageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
        :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public object Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((object)(this.results[0]));
        }
    }
}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
//public delegate void getResourceStatusCompletedEventHandler(object sender, getResourceStatusCompletedEventArgs e);

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getResourceStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    //private object[] results;

    //internal getResourceStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
    //    :
    //        base(exception, cancelled, userState)
    //{
    //    this.results = results;
    //}

    ///// <remarks/>
    //public object Result
    //{
    //    get
    //    {
    //        this.RaiseExceptionIfNecessary();
    //        return ((object)(this.results[0]));
    //    }
    //}
}
