//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class AddChapter {
        protected System.Web.UI.WebControls.Panel pnlTemplate;
        protected System.Web.UI.WebControls.Label lblChapter;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.HiddenField hdnListitemStatus;
        protected System.Web.UI.WebControls.ImageButton imgShowHide;
        protected System.Web.UI.WebControls.DropDownList cboDWBCountry;
        protected System.Web.UI.WebControls.DropDownList cboAssetType;
        protected System.Web.UI.WebControls.DropDownList cboColumnName;
        protected System.Web.UI.WebControls.TextBox txtCriteria;
        protected System.Web.UI.WebControls.Button btnSearch;
        protected System.Web.UI.WebControls.Label lblAssetValue;
        protected System.Web.UI.WebControls.ListBox lstAssetValues;
        protected System.Web.UI.WebControls.DropDownList cboTemplate;
        protected System.Web.UI.WebControls.TextBox txtChapterTitle;
        protected System.Web.UI.WebControls.TextBox txtDescription;
        protected System.Web.UI.WebControls.Button cmdOK;
        protected System.Web.UI.WebControls.Button cmdCancel;
    }
}
