//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class BatchImportConfiguration {
        protected System.Web.UI.WebControls.Panel pnlTemplate;
        protected System.Web.UI.WebControls.Label lblWellBookHeading;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.HiddenField hdnResetStatus;
        protected System.Web.UI.WebControls.Panel BatchImportConfigurationGridViewPanelID;
        protected System.Web.UI.WebControls.GridView grdBatchImportConfiguration;
        protected System.Web.UI.WebControls.Button btnSaveAndContinue;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.Button btnReset;
        protected System.Web.UI.WebControls.Button btnResetToDefaultPath;
        protected System.Web.UI.WebControls.Button btnCancel;
    }
}
