//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class BatchImportStatus {
        protected System.Web.UI.WebControls.Label lblStatusMsg;
        protected System.Web.UI.WebControls.LinkButton lnkShowBatchImportStatus;
    }
}
