//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class BatchImportConfirmation {
        protected System.Web.UI.WebControls.Label lblBookName;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.Panel pnlGrid;
        protected System.Web.UI.WebControls.GridView gvBatchImportConfirmation;
        protected System.Web.UI.WebControls.Button btnContinue;
        protected System.Web.UI.WebControls.Button btnCancel;
    }
}
