//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class ChangePageOwner {
        protected System.Web.UI.WebControls.Panel pnlTemplate;
        protected System.Web.UI.WebControls.Label lblWellBookHeading;
        protected System.Web.UI.WebControls.Label lblBookTitle;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.HiddenField hdnListitemStatus;
        protected System.Web.UI.WebControls.Label lblSelectCurrentOwner;
        protected System.Web.UI.WebControls.DropDownList cboOwner;
        protected System.Web.UI.WebControls.Panel pnlRadiobuttonListID;
        protected System.Web.UI.WebControls.RadioButtonList rblStatus;
        protected System.Web.UI.WebControls.Panel pnlFilterOptions;
        protected System.Web.UI.WebControls.Label lblPageTitle;
        protected System.Web.UI.WebControls.DropDownList cboPageTitle;
        protected System.Web.UI.WebControls.Label lblChapterName;
        protected System.Web.UI.WebControls.ListBox lstChapterNames;
        protected System.Web.UI.WebControls.Button btnFilter;
        protected System.Web.UI.WebControls.Button btnReset;
        protected System.Web.UI.WebControls.Panel PageOwnerGridViewPanelID;
        protected System.Web.UI.WebControls.Label lblNewOwner;
        protected System.Web.UI.WebControls.DropDownList cboNewOwner;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.Button btnSaveAndChangeMore;
        protected System.Web.UI.WebControls.Button btnCancel;
    }
}
