//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class ChapterMaintenance {
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.TextBox txtAssetType;
        protected System.Web.UI.WebControls.Button btnPrint;
        protected System.Web.UI.WebControls.TextBox txtAssetValue;
        protected System.Web.UI.WebControls.TextBox txtTemplateTitle;
        protected System.Web.UI.WebControls.TextBox txtDescription;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hdnListitemStatus;
        protected System.Web.UI.WebControls.HiddenField hdnIncludeStoryBoard;
        protected System.Web.UI.WebControls.HiddenField hdnIncludePageTitle;
        protected System.Web.UI.WebControls.HiddenField hdnPrintMyPages;
        protected System.Web.UI.WebControls.HiddenField hdnIncludeFilter;
        protected System.Web.UI.WebControls.HiddenField hdnSignedOffPages;
        protected System.Web.UI.WebControls.HiddenField hdnEmptyPages;
        protected System.Web.UI.WebControls.HiddenField hdnPageType;
        protected System.Web.UI.WebControls.HiddenField hdnPageName;
        protected System.Web.UI.WebControls.HiddenField hdnDiscipline;
    }
}
