//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer.User_Controls {
    
    public partial class EditStaffPrivilege {
        protected System.Web.UI.WebControls.Panel pnlTemp;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.Label lblPrivilege;
        protected System.Web.UI.WebControls.DropDownList cboEditPrivileges;
        protected System.Web.UI.WebControls.Button cmdOK;
        protected System.Web.UI.WebControls.Button cmdCancel;
    }
}
