//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class MasterPages {
        protected System.Web.UI.WebControls.Panel pnlMasterPage;
        protected System.Web.UI.WebControls.Label lblMasterPage;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.HiddenField hdnListItemStatus;
        protected System.Web.UI.WebControls.TextBox txtPageTitle;
        protected System.Web.UI.WebControls.TextBox txtTitleTemplate;
        protected System.Web.UI.WebControls.DropDownList cboAssetType;
        protected System.Web.UI.WebControls.DropDownList cboDiscipline;
        protected System.Web.UI.WebControls.TextBox txtSOP;
        protected System.Web.UI.WebControls.DropDownList cboConnectionType;
        protected System.Web.UI.WebControls.Label lblTemplates;
        protected System.Web.UI.WebControls.ListBox lstTemplates;
        protected System.Web.UI.WebControls.Button cmdOK;
        protected System.Web.UI.WebControls.Button cmdCancel;
    }
}
