//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class PageStoryBoard {
        protected System.Web.UI.WebControls.Panel pnlStoryBoard;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.Table Table1;
        protected System.Web.UI.WebControls.TableHeaderRow TableHeaderRow1;
        protected System.Web.UI.WebControls.TableHeaderCell TableHeaderCell1;
        protected System.Web.UI.WebControls.TableRow Row1;
        protected System.Web.UI.WebControls.TableCell MetaData1;
        protected System.Web.UI.WebControls.TableCell Information1;
        protected System.Web.UI.WebControls.TextBox txtPageType;
        protected System.Web.UI.WebControls.TableRow Row2;
        protected System.Web.UI.WebControls.TableCell MetaData2;
        protected System.Web.UI.WebControls.TableCell Information2;
        protected System.Web.UI.WebControls.TextBox txtPageTitle;
        protected System.Web.UI.WebControls.TableRow Row3;
        protected System.Web.UI.WebControls.TableCell MetaData3;
        protected System.Web.UI.WebControls.TableCell Information3;
        protected System.Web.UI.WebControls.TextBox txtConnectionType;
        protected System.Web.UI.WebControls.TableRow Row4;
        protected System.Web.UI.WebControls.TableCell MetaData4;
        protected System.Web.UI.WebControls.TableCell Information4;
        protected System.Web.UI.WebControls.TextBox txtSource;
        protected System.Web.UI.WebControls.TableRow Row5;
        protected System.Web.UI.WebControls.TableCell MetaData5;
        protected System.Web.UI.WebControls.TableCell Information5;
        protected System.Web.UI.WebControls.TextBox txtDiscipline;
        protected System.Web.UI.WebControls.TableRow Row6;
        protected System.Web.UI.WebControls.TableCell MetaData6;
        protected System.Web.UI.WebControls.TableCell Information6;
        protected System.Web.UI.WebControls.TextBox txtMasterPageName;
        protected System.Web.UI.WebControls.TableRow Row7;
        protected System.Web.UI.WebControls.TableCell MetaData7;
        protected System.Web.UI.WebControls.TableCell Information7;
        protected System.Web.UI.WebControls.TextBox txtApplicationGeneratingPage;
        protected System.Web.UI.WebControls.TableRow Row8;
        protected System.Web.UI.WebControls.TableCell MetaData8;
        protected System.Web.UI.WebControls.TableCell Information8;
        protected System.Web.UI.WebControls.TextBox txtApplicationTemplate;
        protected System.Web.UI.WebControls.TableRow Row9;
        protected System.Web.UI.WebControls.TableCell MetaData9;
        protected System.Web.UI.WebControls.TableCell Information9;
        protected System.Web.UI.WebControls.TextBox txtSOP;
        protected System.Web.UI.WebControls.TableRow Row10;
        protected System.Web.UI.WebControls.TableCell MetaData10;
        protected System.Web.UI.WebControls.TableCell Information10;
        protected System.Web.UI.WebControls.TextBox txtCreatedBy;
        protected System.Web.UI.WebControls.TableRow Row11;
        protected System.Web.UI.WebControls.TableCell MetaData11;
        protected System.Web.UI.WebControls.TableCell Information11;
        protected System.Web.UI.WebControls.TextBox txtCreationDate;
        protected System.Web.UI.WebControls.TableRow Row12;
        protected System.Web.UI.WebControls.TableCell MetaData12;
        protected System.Web.UI.WebControls.TableCell Information12;
        protected System.Web.UI.WebControls.TextBox txtPageOwner;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidUserName;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidBookOwner;
    }
}
