//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class RankStaff {
        protected System.Web.UI.WebControls.HiddenField hdnParentName;
        protected System.Web.UI.WebControls.HiddenField hdnParentID;
        protected System.Web.UI.WebControls.Panel pnlTemplate;
        protected System.Web.UI.WebControls.Label lblHeading;
        protected System.Web.UI.WebControls.Label lblParentName;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.Label lblDiscipline;
        protected System.Web.UI.WebControls.DropDownList cboDiscipline;
        protected System.Web.UI.WebControls.Panel pnlPrivileges;
        protected System.Web.UI.WebControls.Label lblRankStaffs;
        protected Shell.SharePoint.DWB.DualListControl.DualList dualListPrivileges;
        protected System.Web.UI.WebControls.Button cmdSave;
        protected System.Web.UI.WebControls.Button cmdSaveContinue;
        protected System.Web.UI.WebControls.Button cmdCancel;
    }
}
