//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class StoryBoardConfirmation {
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.Label lblPageTitleConfirm;
        protected System.Web.UI.WebControls.RadioButtonList rblPageTitleConfirm;
        protected System.Web.UI.WebControls.Label lblStoryBoardInfo;
        protected System.Web.UI.WebControls.RadioButtonList rblStoryBoardConfirm;
        protected System.Web.UI.WebControls.Panel pnlPrintMyPages;
        protected System.Web.UI.WebControls.CheckBox chkPrintMyPagesOnly;
        protected System.Web.UI.WebControls.Panel pnlIncludeFilter;
        protected System.Web.UI.WebControls.RadioButtonList rblIncludeFilter;
        protected System.Web.UI.WebControls.Panel pnlFilterOptions;
        protected System.Web.UI.WebControls.Label lblPageSignedOff;
        protected System.Web.UI.WebControls.CheckBoxList chklPageSignedOff;
        protected System.Web.UI.WebControls.Label lblPageEmpty;
        protected System.Web.UI.WebControls.CheckBoxList chklPageEmpty;
        protected System.Web.UI.WebControls.Label lblPageType;
        protected System.Web.UI.WebControls.CheckBoxList chkPageType;
        protected System.Web.UI.WebControls.Label lblPageName;
        protected System.Web.UI.WebControls.DropDownList cboPageName;
        protected System.Web.UI.WebControls.Label lblDiscipline;
        protected System.Web.UI.WebControls.DropDownList cboDisciplineName;
        protected System.Web.UI.WebControls.Button btnCancel;
    }
}
