//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class TeamRegistration {
        protected System.Web.UI.WebControls.HiddenField hdnTeamTerminated;
        protected System.Web.UI.WebControls.Panel pnlTemplate;
        protected System.Web.UI.WebControls.Label lblAddTeam;
        protected System.Web.UI.WebControls.Label lblTeam;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.Label lblName;
        protected System.Web.UI.WebControls.TextBox txtTeamName;
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.DropDownList cboAssetOwner;
        protected System.Web.UI.WebControls.Button cmdOK;
        protected System.Web.UI.WebControls.Button cmdCancel;
    }
}
