//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class Template {
        protected System.Web.UI.WebControls.HiddenField hdnTemplateID;
        protected System.Web.UI.WebControls.HiddenField hdnTerminated;
        protected System.Web.UI.WebControls.Panel pnlTemplate;
        protected System.Web.UI.WebControls.Label lblTemplateHeading;
        protected System.Web.UI.WebControls.Label lblTemplateTitle;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.Label lblTitle;
        protected System.Web.UI.WebControls.TextBox txtTemplateTitle;
        protected System.Web.UI.WebControls.Label lblAssetType;
        protected System.Web.UI.WebControls.DropDownList cboAssetType;
        protected System.Web.UI.WebControls.Label lblCopyMasterPage;
        protected System.Web.UI.WebControls.DropDownList cboTemplates;
        protected System.Web.UI.WebControls.Button cmdOK;
        protected System.Web.UI.WebControls.Button cmdCancel;
    }
}
