//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class TemplatePages {
        protected System.Web.UI.WebControls.HiddenField hdnTemplateType;
        protected System.Web.UI.WebControls.Panel pnlTemplate;
        protected System.Web.UI.WebControls.Label lblTemplateHeading;
        protected System.Web.UI.WebControls.Label lblTemplateTitle;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.Panel pnlMasterPages;
        protected Shell.SharePoint.DWB.DualListControl.DualList duallistTemplatePages;
        protected System.Web.UI.WebControls.Button cmdSave;
        protected System.Web.UI.WebControls.Button cmdCancel;
    }
}
