//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class UploadDocument {
        protected System.Web.UI.WebControls.Panel AdvancedSearchContent;
        protected System.Web.UI.WebControls.Label lblErrorMessage;
        protected System.Web.UI.HtmlControls.HtmlInputFile fileUploader;
        protected System.Web.UI.WebControls.Button btnUpload;
        protected System.Web.UI.HtmlControls.HtmlInputButton btnCancel;
        protected System.Web.UI.HtmlControls.HtmlInputButton btnClose;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidPageId;
    }
}
