//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class UserRegistration {
        protected System.Web.UI.WebControls.HiddenField hdnUserTerminated;
        protected System.Web.UI.WebControls.Panel pnlTemplate;
        protected System.Web.UI.WebControls.Label lblAddUser;
        protected System.Web.UI.WebControls.Label lblUser;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.Label lblUserId;
        protected System.Web.UI.WebControls.DropDownList cboUserId;
        protected System.Web.UI.WebControls.Label lblIsAdmin;
        protected System.Web.UI.WebControls.CheckBox cbIsAdmin;
        protected System.Web.UI.WebControls.Label lblDiscipline;
        protected System.Web.UI.WebControls.DropDownList cboDiscipline;
        protected System.Web.UI.HtmlControls.HtmlGenericControl spnTeamMandotory;
        protected System.Web.UI.WebControls.Label lblTeam;
        protected System.Web.UI.WebControls.ListBox lstTeams;
        protected System.Web.UI.WebControls.Button cmdOK;
        protected System.Web.UI.WebControls.Button cmdCancel;
    }
}
