//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class UserUploaded {
        protected System.Web.UI.WebControls.Panel AdvancedSearchContent;
        protected System.Web.UI.WebControls.Label lblErrorMessage;
        protected System.Web.UI.WebControls.Label lblTitleTemplate;
        protected System.Web.UI.WebControls.Label lblOwner;
        protected System.Web.UI.WebControls.Label lblSignedOff;
        protected System.Web.UI.WebControls.Label lblModifiedDate;
        protected System.Web.UI.HtmlControls.HtmlInputButton btnSignOff;
        protected System.Web.UI.HtmlControls.HtmlInputButton btnUpdate;
        protected System.Web.UI.WebControls.Button btnPrint;
        protected System.Web.UI.HtmlControls.HtmlGenericControl docviewerdiv;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidPageId;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidtype3uploaded;
        protected System.Web.UI.WebControls.HiddenField hdnIncludeStoryBoard;
        protected System.Web.UI.WebControls.HiddenField hdnIncludePageTitle;
        protected System.Web.UI.WebControls.Button btnFirePostBack;
    }
}
