//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class WellBook {
        protected System.Web.UI.WebControls.Panel pnlTemplate;
        protected System.Web.UI.WebControls.Label lblWellBookHeading;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.HiddenField hdnListitemStatus;
        protected System.Web.UI.WebControls.TextBox txtWellBookTitle;
        protected System.Web.UI.WebControls.DropDownList cboTeam;
        protected System.Web.UI.WebControls.DropDownList cboOwner;
        protected System.Web.UI.WebControls.Button cmdOK;
        protected System.Web.UI.WebControls.Button cmdCancel;
    }
}
