//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class WellBookPublishConfirmation {
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.Panel pnlPublishBook;
        protected System.Web.UI.WebControls.Panel pnlPublishProcess;
        protected System.Web.UI.WebControls.Label lblBookName;
        protected System.Web.UI.WebControls.Label lblPublish;
        protected System.Web.UI.WebControls.GridView grdWellBookSummary;
        protected System.Web.UI.WebControls.TextBox txtNewBookName;
        protected System.Web.UI.WebControls.Button cmdContinuePublish;
        protected System.Web.UI.WebControls.Button cmdCancel;
        protected System.Web.UI.WebControls.Panel pnlBookPublished;
        protected System.Web.UI.WebControls.Label lblPublishStatus;
        protected System.Web.UI.WebControls.Button btnClose;
    }
}
