//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DWB.UserInterfaceLayer {
    
    public partial class WellBookSummary {
        protected System.Web.UI.WebControls.Panel pnlTemplate;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.HiddenField hdnPageOwner;
        protected System.Web.UI.WebControls.HiddenField hdnIncludeStoryBoard;
        protected System.Web.UI.WebControls.HiddenField hdnIncludePageTitle;
        protected System.Web.UI.WebControls.HiddenField hdnPrintMyPages;
        protected System.Web.UI.WebControls.HiddenField hdnIncludeFilter;
        protected System.Web.UI.WebControls.HiddenField hdnSignedOffPages;
        protected System.Web.UI.WebControls.HiddenField hdnEmptyPages;
        protected System.Web.UI.WebControls.HiddenField hdnPageType;
        protected System.Web.UI.WebControls.HiddenField hdnPageName;
        protected System.Web.UI.WebControls.HiddenField hdnDiscipline;
        protected System.Web.UI.WebControls.HiddenField hdnWellBookId;
        protected System.Web.UI.WebControls.TextBox txtTeam;
        protected System.Web.UI.WebControls.Label lblAssetValue;
        protected System.Web.UI.WebControls.TextBox txtOwner;
        protected System.Web.UI.WebControls.TextBox txtSignOffStatus;
        protected System.Web.UI.WebControls.Button btnSignOff;
        protected System.Web.UI.WebControls.Button btnPrint;
        protected System.Web.UI.WebControls.Button btnBatchImport;
        protected System.Web.UI.WebControls.GridView grdWellBookSummary;
        protected System.Web.UI.WebControls.Button btnCustomiseChapters;
        protected System.Web.UI.WebControls.Button btnFilterPages;
        protected System.Web.UI.HtmlControls.HtmlGenericControl diveWBCustomiseChapters;
        protected System.Web.UI.HtmlControls.HtmlInputCheckBox chkSelectDeselectAll;
        protected Telerik.Web.UI.RadListBox radLstChapters;
        protected System.Web.UI.WebControls.Button btnApply;
        protected System.Web.UI.WebControls.Button btnApplyAndSave;
    }
}
