//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class AHDTVDConverter {
        protected System.Web.UI.WebControls.Panel pnlSoapError;
        protected System.Web.UI.WebControls.Label lblErrorMessage;
        protected System.Web.UI.WebControls.Button btn_goBack;
        protected System.Web.UI.WebControls.Panel pnlConverterContent;
        protected System.Web.UI.WebControls.Label lblWellbore;
        protected System.Web.UI.WebControls.DropDownList drpWellbore;
        protected System.Web.UI.WebControls.Label lblDepthReference;
        protected System.Web.UI.WebControls.DropDownList drpDepthReference;
        protected System.Web.UI.WebControls.Label lblDepthUnit;
        protected System.Web.UI.WebControls.RadioButton rdoDepthUnitsFeet;
        protected System.Web.UI.WebControls.RadioButton rdoDepthUnitsMetres;
        protected System.Web.UI.WebControls.Panel pnlTable;
        protected System.Web.UI.WebControls.Label lblCountry;
        protected System.Web.UI.WebControls.Label lblProject;
        protected System.Web.UI.WebControls.Label lblWellborePath;
        protected System.Web.UI.WebControls.Label lblPDL;
        protected System.Web.UI.WebControls.Label lblResultCountry;
        protected System.Web.UI.WebControls.Label lblResultProject;
        protected System.Web.UI.WebControls.Label lblResultWellborePath;
        protected System.Web.UI.WebControls.Label lblResultPDL;
        protected System.Web.UI.WebControls.Button btnConvert;
        protected System.Web.UI.WebControls.Button btnClear;
        protected System.Web.UI.WebControls.Panel pnl;
        protected System.Web.UI.WebControls.Button btnConvert1;
        protected System.Web.UI.WebControls.Button btnClear1;
        protected System.Web.UI.WebControls.Button btnAddRows;
        protected System.Web.UI.WebControls.Panel pnlTableErrorMessage;
        protected System.Web.UI.WebControls.Label lblTableErrorMessage;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidSelectedCriteriaName;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidReportSelectRow;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidSelectedRows;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidRows;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidDrpValue;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidDepthMode;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hdnTabIndex;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hdnFirstAHDepthValue;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hdnLastAHDepthValue;
        protected System.Web.UI.WebControls.HiddenField hidDepthRefDefaultUnit;
    }
}
