//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class AssetTree {
        protected System.Web.UI.WebControls.Panel pnlMain;
        protected Telerik.Web.UI.RadTreeView trvAssetTree;
        protected System.Web.UI.WebControls.HiddenField hidPageNumber;
        protected System.Web.UI.WebControls.HiddenField hidClickedPage;
        protected System.Web.UI.WebControls.HiddenField hidSearchText;
        protected System.Web.UI.WebControls.HiddenField hidSearchBoxStatus;
        protected System.Web.UI.WebControls.HiddenField hidRecordCount;
        protected System.Web.UI.UpdatePanel updatePanelAssetTree;
    }
}
