//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class EDMReport {
        protected System.Web.UI.WebControls.Panel EDMReportContent;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdDDLAssets;
        protected System.Web.UI.WebControls.CheckBoxList chbLstReportLevel;
        protected System.Web.UI.WebControls.DropDownList cboTimePeriod;
        protected System.Web.UI.WebControls.TextBox txtStartDate;
        protected System.Web.UI.WebControls.TextBox txtEndDate;
        protected System.Web.UI.WebControls.RadioButtonList rbLstYesNo;
        protected System.Web.UI.WebControls.RadioButtonList rbLstDisplayFormat;
        protected System.Web.UI.WebControls.Button btnSubmit;
    }
}
