//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class EPCatalogFilter {
        protected System.Web.UI.HtmlControls.HtmlTable tblEPCatalogFilter;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDates;
        protected System.Web.UI.HtmlControls.HtmlTableCell Td1;
        protected System.Web.UI.HtmlControls.HtmlTableCell Td2;
        protected System.Web.UI.WebControls.TextBox txtStartDate;
        protected System.Web.UI.WebControls.TextBox txtEndDate;
        protected System.Web.UI.WebControls.Image imgPublishedDate;
        protected System.Web.UI.WebControls.TextBox txtAUTHORNAME;
        protected System.Web.UI.WebControls.Image imgAuthorName;
        protected System.Web.UI.WebControls.RadioButtonList rbLstEPCatalogSrchType;
        protected System.Web.UI.WebControls.TextBox txtBxSrchGrpOfProdType;
        protected Telerik.Web.UI.RadListBox lstGrpOfProdType;
        protected System.Web.UI.WebControls.TextBox txtBxSrchRgnGrpOfProdType;
        protected Telerik.Web.UI.RadListBox lstRgnGrpOfProdType;
        protected System.Web.UI.WebControls.TextBox txtBxSrchAdditonalProdType;
        protected Telerik.Web.UI.RadListBox lstAdditonalProdType;
        protected Telerik.Web.UI.RadListBox lstSelectedProdType;
        protected System.Web.UI.WebControls.Image imgSelectedProdType;
        protected System.Web.UI.WebControls.Button cmdSearch;
        protected System.Web.UI.WebControls.Button cmdReset;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidIdentifiers;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidColumnName;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidAssetType;
    }
}
