//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class FeedbackUI {
        protected System.Web.UI.WebControls.Panel pnlFeedback;
        protected System.Web.UI.WebControls.Label lblErrorMessage;
        protected System.Web.UI.WebControls.RadioButtonList rdoFeedback;
        protected System.Web.UI.WebControls.RadioButtonList rdoRating;
        protected System.Web.UI.WebControls.TextBox txtReasonForRating;
        protected System.Web.UI.WebControls.TextBox txtAdditionalInformation;
        protected System.Web.UI.WebControls.DropDownList ddlPageName;
        protected System.Web.UI.HtmlControls.HtmlAnchor lnkRemove;
        protected System.Web.UI.WebControls.TextBox txtPageLevelComment;
        protected System.Web.UI.WebControls.Button cmdSubmit;
        protected System.Web.UI.WebControls.Button cmdReset;
        protected System.Web.UI.WebControls.Panel pnlConfirmFeedback;
        protected System.Web.UI.WebControls.Label lblMessage;
        protected System.Web.UI.WebControls.Button cmdClose;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidFileName;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidFilePath;
    }
}
