//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class FieldAdvSearch {
        protected System.Web.UI.WebControls.PlaceHolder plcAJAX;
        protected System.Web.UI.WebControls.Panel AdvancedSearchContent;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.RadioButtonList rdblSearchCond;
        protected System.Web.UI.WebControls.DropDownList cboSavedSearch;
        protected System.Web.UI.WebControls.Image imgSavedSearch;
        protected System.Web.UI.WebControls.Button cmdSavedSearchButton;
        protected System.Web.UI.HtmlControls.HtmlInputButton btnResetButton;
        protected System.Web.UI.WebControls.DropDownList cboSearchCriteria;
        protected System.Web.UI.HtmlControls.HtmlInputFile fileUploader;
        protected System.Web.UI.WebControls.TextBox txtField_Identifier;
        protected System.Web.UI.WebControls.Image imgIdentifier;
        protected System.Web.UI.WebControls.TextBox txtDescription;
        protected System.Web.UI.WebControls.Image imgDescription;
        protected System.Web.UI.WebControls.DropDownList lstCountry;
        protected System.Web.UI.WebControls.Image imgCountry;
        protected System.Web.UI.WebControls.TextBox txtOwner;
        protected System.Web.UI.WebControls.Image imgOwner;
        protected Telerik.Web.UI.RadComboBox radCboFieldName;
        protected System.Web.UI.WebControls.Image imgFieldName;
        protected System.Web.UI.WebControls.TextBox txtFieldType;
        protected System.Web.UI.WebControls.Image imgTypeofField;
        protected Telerik.Web.UI.RadComboBox radCboOperator;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdOperator;
        protected System.Web.UI.WebControls.Image imgOperator;
        protected System.Web.UI.WebControls.TextBox txtCurrentStatus;
        protected System.Web.UI.WebControls.Image imgCurrentStatus;
        protected Telerik.Web.UI.RadComboBox radCboBasinName;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdBasinName;
        protected System.Web.UI.WebControls.Image imgBasinName;
        protected System.Web.UI.WebControls.DropDownList cboOperationalEnv;
        protected System.Web.UI.WebControls.Image imgOperationalEnv;
        protected System.Web.UI.WebControls.RadioButtonList rdblTectonicClassification;
        protected System.Web.UI.WebControls.DropDownList cboTectonicSetting;
        protected System.Web.UI.WebControls.DropDownList cboTectonicSettingKle;
        protected System.Web.UI.WebControls.Image imgTectonicSetting;
        protected System.Web.UI.WebControls.DropDownList cboReserveMagOil;
        protected System.Web.UI.WebControls.Image imgReserveMagnitudeOil;
        protected System.Web.UI.WebControls.TextBox txtOilInPlace;
        protected System.Web.UI.WebControls.Image imgOilInPlace;
        protected System.Web.UI.WebControls.DropDownList cboReserveMagGas;
        protected System.Web.UI.WebControls.TextBox txtGasInitiallyInPlace;
        protected System.Web.UI.WebControls.Image imgGasInitiallyInPlace;
        protected System.Web.UI.WebControls.TextBox txtCondensateRecovery;
        protected System.Web.UI.WebControls.Image imgCondensateRecoveryFactor;
        protected System.Web.UI.WebControls.TextBox txtCondensateInPlace;
        protected System.Web.UI.WebControls.Image imgCondensateInPlace;
        protected System.Web.UI.WebControls.TextBox txtNoOfWells;
        protected System.Web.UI.WebControls.Image imgNoOfWells;
        protected System.Web.UI.WebControls.TextBox txtNoOfProducers;
        protected System.Web.UI.WebControls.Image imgNoOfProducers;
        protected System.Web.UI.WebControls.TextBox txtNoOfInjectors;
        protected System.Web.UI.WebControls.Image imgNoOfInjector;
        protected System.Web.UI.WebControls.TextBox txtPorosity;
        protected System.Web.UI.WebControls.Image imgPorosityMax;
        protected System.Web.UI.WebControls.Label lblSRPPorosityInfo;
        protected System.Web.UI.WebControls.TextBox txtPermeability;
        protected System.Web.UI.WebControls.Image imgPermeabilityMax;
        protected System.Web.UI.WebControls.Label lblSRPPermeabilityInfo;
        protected System.Web.UI.WebControls.Label lblSRPInfo;
        protected System.Web.UI.WebControls.TextBox txtSaveSearch;
        protected System.Web.UI.WebControls.Image imgSearchName;
        protected System.Web.UI.WebControls.CheckBox chbShared;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdSaveSearch;
        protected System.Web.UI.WebControls.Button cmdSearch;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdReset;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidWordContent;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidRadContent;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidTechContent;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidSrpControlSectionId;
    }
}
