//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class FieldAdvPopup {
        protected System.Web.UI.WebControls.Label lblName;
        protected System.Web.UI.WebControls.ListBox lstFieldNames;
        protected System.Web.UI.WebControls.Label lblMessage;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdSelect;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdClose;
    }
}
