//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class FunctionalityUsageAdvReport {
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.ListBox lstFURSearchName;
        protected System.Web.UI.WebControls.Image imgSearchNam;
        protected System.Web.UI.WebControls.ListBox lstUserName;
        protected System.Web.UI.WebControls.Image imgUserName;
        protected System.Web.UI.WebControls.RadioButton rbCurrentYear;
        protected System.Web.UI.WebControls.RadioButton rbLast1Year;
        protected System.Web.UI.WebControls.RadioButton rbLast2Year;
        protected System.Web.UI.WebControls.RadioButton rbCurrentMonth;
        protected System.Web.UI.WebControls.RadioButton rbLast6Month;
        protected System.Web.UI.WebControls.RadioButton rbSelectDates;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDates;
        protected System.Web.UI.HtmlControls.HtmlTableCell Td1;
        protected System.Web.UI.WebControls.TextBox txtStartDate;
        protected System.Web.UI.HtmlControls.HtmlTableCell Td2;
        protected System.Web.UI.WebControls.TextBox txtEndDate;
        protected System.Web.UI.WebControls.Button cmdSearch;
    }
}
