//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class GeoPressure {
        protected System.Web.UI.WebControls.Panel GeoPressureFilterContent;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.DropDownList cboTestType;
        protected System.Web.UI.WebControls.DropDownList cboDataSource;
        protected System.Web.UI.WebControls.Button btnSubmit;
    }
}
