//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class InterpolatedLogs {
        protected System.Web.UI.HtmlControls.HtmlTableRow trFilterOptions;
        protected System.Web.UI.HtmlControls.HtmlGenericControl lblChnage;
        protected System.Web.UI.HtmlControls.HtmlGenericControl lblChange1;
        protected System.Web.UI.WebControls.DropDownList ddlWellBore;
        protected System.Web.UI.WebControls.DropDownList ddlProjectionSystem;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDepthInterval;
        protected System.Web.UI.WebControls.DropDownList ddlDepthInterval;
        protected System.Web.UI.WebControls.Label lblDepthInterval;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDataPreferences;
        protected System.Web.UI.WebControls.DropDownList ddlDataPreference;
        protected System.Web.UI.WebControls.TextBox txtbxFrom;
        protected System.Web.UI.WebControls.Label lblFrom;
        protected System.Web.UI.WebControls.TextBox txtbxTo;
        protected System.Web.UI.WebControls.Label lblTo;
        protected System.Web.UI.HtmlControls.HtmlTableRow trMode;
        protected System.Web.UI.WebControls.DropDownList ddlMode;
        protected System.Web.UI.WebControls.Button btnSearch;
    }
}
