//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class LogFieldAdvSearch {
        protected System.Web.UI.WebControls.Panel AdvancedSearchContent;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.DropDownList cboSavedSearch;
        protected System.Web.UI.WebControls.Image imgSavedSearch;
        protected System.Web.UI.WebControls.RadioButton rdoDepthUnitsFeet;
        protected System.Web.UI.WebControls.RadioButton rdoDepthUnitsMetres;
        protected System.Web.UI.WebControls.TextBox txtFieldName;
        protected System.Web.UI.WebControls.Image imgFieldName;
        protected System.Web.UI.WebControls.TextBox txtCurveTopDepth;
        protected System.Web.UI.WebControls.Image imgCurveTopDepth;
        protected System.Web.UI.WebControls.TextBox txtCurveBottomDepth;
        protected System.Web.UI.WebControls.Image imgCurveBottomDepth;
        protected System.Web.UI.WebControls.TextBox txtSaveSearch;
        protected System.Web.UI.WebControls.Image imgSearchName;
        protected System.Web.UI.WebControls.CheckBox chbShared;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdSaveSearch;
        protected System.Web.UI.WebControls.Button cmdSearch;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdReset;
    }
}
