//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI {
    
    public partial class ManageTeam {
        protected System.Web.UI.WebControls.Panel AdvancedSearchContent;
        protected System.Web.UI.WebControls.Label lblAddTeam;
        protected System.Web.UI.WebControls.Label lblTeam;
        protected System.Web.UI.WebControls.Label lblErrorMessage;
        protected System.Web.UI.WebControls.TextBox txtTEAMNAME;
        protected System.Web.UI.WebControls.ListBox lstTeamOwner;
        protected System.Web.UI.WebControls.DropDownList cboPROJECTNAME;
        protected System.Web.UI.WebControls.DropDownList cboMAPBOOKMARK;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.HtmlControls.HtmlInputButton btnCancel;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidTeamOwner;
    }
}
