//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI {
    
    public partial class ManageStaff {
        protected System.Web.UI.WebControls.Panel AdvancedSearchContent;
        protected System.Web.UI.WebControls.Label lblManageStaffTitle;
        protected System.Web.UI.WebControls.Label lblErrorMessage;
        protected System.Web.UI.WebControls.Panel pnlStaff;
        protected Shell.SharePoint.DWB.DualListControl.DualList dualManageStaff;
        protected System.Web.UI.WebControls.Button cmdSave;
        protected System.Web.UI.WebControls.Button cmdCancel;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidTeamOwnerUserId;
    }
}
