//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class PARSAdvSearch {
        protected System.Web.UI.WebControls.Panel AdvancedSearchContent;
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.DropDownList cboSavedSearch;
        protected System.Web.UI.WebControls.Image imgSavedSearch;
        protected System.Web.UI.WebControls.Button btnSearch;
        protected System.Web.UI.HtmlControls.HtmlInputButton btnReset;
        protected System.Web.UI.WebControls.DropDownList cboSearchCriteria;
        protected System.Web.UI.HtmlControls.HtmlInputFile fileUploader;
        protected System.Web.UI.WebControls.TextBox txtXMTITLE;
        protected System.Web.UI.WebControls.Image imgTitle;
        protected System.Web.UI.WebControls.TextBox txtXMDESCRIPTION;
        protected System.Web.UI.WebControls.Image imgDescription;
        protected System.Web.UI.WebControls.TextBox txtXMPROJECTNAME;
        protected System.Web.UI.WebControls.Image imgProjectName;
        protected System.Web.UI.WebControls.TextBox txtXMMILESTONE;
        protected System.Web.UI.WebControls.Image imgMilestone;
        protected System.Web.UI.WebControls.TextBox txtXMBASIN;
        protected System.Web.UI.WebControls.Image imgBasin;
        protected System.Web.UI.WebControls.TextBox txtXMFIELD;
        protected System.Web.UI.WebControls.Image imgField;
        protected System.Web.UI.WebControls.TextBox txtXMASSET;
        protected System.Web.UI.WebControls.Image imgAsset;
        protected System.Web.UI.WebControls.TextBox txtXMCOUNTRY;
        protected System.Web.UI.WebControls.Image imgCountry;
        protected System.Web.UI.WebControls.TextBox txtXMOWNER;
        protected System.Web.UI.WebControls.Image imgDataOwner;
        protected System.Web.UI.WebControls.TextBox txtXMOWNERORGANISATION;
        protected System.Web.UI.WebControls.Image imgOwnerOrganisation;
        protected System.Web.UI.WebControls.RadioButton rbLastWeek;
        protected System.Web.UI.WebControls.RadioButton rbLastMonth;
        protected System.Web.UI.WebControls.RadioButton rbLastYear;
        protected System.Web.UI.WebControls.RadioButton rbSelectDates;
        protected System.Web.UI.HtmlControls.HtmlTableRow trDates;
        protected System.Web.UI.HtmlControls.HtmlTableCell Td1;
        protected System.Web.UI.WebControls.TextBox txtStartDate;
        protected System.Web.UI.HtmlControls.HtmlTableCell Td2;
        protected System.Web.UI.WebControls.TextBox txtEndDate;
        protected System.Web.UI.WebControls.CheckBox chbGeographicalSearch;
        protected System.Web.UI.WebControls.TextBox txtMinLatDeg;
        protected System.Web.UI.WebControls.TextBox txtMinLatMin;
        protected System.Web.UI.WebControls.TextBox txtMinLatSec;
        protected System.Web.UI.WebControls.TextBox txtMinLatNS;
        protected System.Web.UI.WebControls.TextBox txtMinLonDeg;
        protected System.Web.UI.WebControls.TextBox txtMinLonMin;
        protected System.Web.UI.WebControls.TextBox txtMinLonSec;
        protected System.Web.UI.WebControls.TextBox txtMinLonEW;
        protected System.Web.UI.WebControls.TextBox txtMaxLatDeg;
        protected System.Web.UI.WebControls.TextBox txtMaxLatMin;
        protected System.Web.UI.WebControls.TextBox txtMaxLatSec;
        protected System.Web.UI.WebControls.TextBox txtMaxLatNS;
        protected System.Web.UI.WebControls.TextBox txtMaxLonDeg;
        protected System.Web.UI.WebControls.TextBox txtMaxLonMin;
        protected System.Web.UI.WebControls.TextBox txtMaxLonSec;
        protected System.Web.UI.WebControls.TextBox txtMaxLonEW;
        protected System.Web.UI.WebControls.TextBox txtSaveSearch;
        protected System.Web.UI.WebControls.Image imgSearchName;
        protected System.Web.UI.WebControls.CheckBox chbShared;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdSaveSearch;
        protected System.Web.UI.WebControls.Button cmdSearch;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdReset;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidWordContent;
    }
}
