//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class QueryBuilder {
        protected System.Web.UI.WebControls.Panel querySearchPanel;
        protected System.Web.UI.WebControls.Panel ExceptionPanel;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.DropDownList cboSavedSearch;
        protected System.Web.UI.WebControls.Image imgSavedSearch;
        protected Telerik.Web.UI.RadTreeView querySearchTree;
        protected System.Web.UI.WebControls.Panel columnSearchPanel;
        protected System.Web.UI.WebControls.ImageButton editButton;
        protected System.Web.UI.WebControls.ImageButton viewButton;
        protected System.Web.UI.WebControls.ImageButton saveButton;
        protected System.Web.UI.WebControls.ImageButton ClearButton;
        protected System.Web.UI.WebControls.ImageButton RunButton;
        protected System.Web.UI.WebControls.CheckBox chbHeaderColumn;
        protected System.Web.UI.WebControls.GridView tblColumnNames;
        protected System.Web.UI.WebControls.TextBox txtSQLQuery;
        protected System.Web.UI.WebControls.TextBox txtSaveSearchName;
        protected System.Web.UI.WebControls.CheckBox chbShared;
        protected System.Web.UI.WebControls.Button btnSaveSearch;
        protected System.Web.UI.WebControls.Button btnSearch;
        protected System.Web.UI.WebControls.Button btnReset;
        protected System.Web.UI.WebControls.XmlDataSource XmlDataSource1;
        protected System.Web.UI.UpdatePanel updatePanelQuerySearch;
    }
}
