//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class RegionFormatSettings {
        protected System.Web.UI.WebControls.Label lblMessage;
        protected System.Web.UI.HtmlControls.HtmlTableRow trSelectLayout;
        protected System.Web.UI.WebControls.DropDownList cboDateFormat;
        protected System.Web.UI.WebControls.Button cmdGoSelect;
        protected System.Web.UI.WebControls.Button btnClose;
    }
}
