//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class ReservoirDepositionalEnvPopup {
        protected Telerik.Web.UI.RadTreeView radTreeViewDepositinalEnv;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidFldDepositional;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidDepostionalLevel;
    }
}
