//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls
{
    
    public partial class ReservoirChronostratPopup {
        protected System.Web.UI.WebControls.Label lblChrono;
        protected System.Web.UI.WebControls.Button btnConfirm;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidFldChronostrat;
        protected System.Web.UI.WebControls.ImageMap imgMapChronostrat;
    }
}
