//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class ReservoirAdvSearch {
        protected System.Web.UI.WebControls.Panel AdvancedSearchContent;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.RadioButtonList rdblSearchCond;
        protected System.Web.UI.WebControls.DropDownList cboSavedSearch;
        protected System.Web.UI.WebControls.Image imgSavedSearch;
        protected System.Web.UI.WebControls.Button cmdSearchButton;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdResetButton;
        protected System.Web.UI.WebControls.DropDownList cboSearchCriteria;
        protected System.Web.UI.HtmlControls.HtmlInputFile fileUploader;
        protected System.Web.UI.WebControls.TextBox txtReservoir_Identifier;
        protected System.Web.UI.WebControls.Image imgIdentifier;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdChronostraticName;
        protected System.Web.UI.WebControls.TextBox txtChronostratigraphy;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdChronostraticClear;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdDepositionalEnv;
        protected System.Web.UI.WebControls.TextBox txtDepositionalEnv;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdDepositionalEnvClear;
        protected System.Web.UI.WebControls.DropDownList cboGrainSizeMean;
        protected System.Web.UI.WebControls.Image imgGrainSizeMean;
        protected Telerik.Web.UI.RadComboBox radCboLithologyMain;
        protected System.Web.UI.WebControls.Image imgLithologyMain;
        protected Telerik.Web.UI.RadComboBox radCboLithologySecondary;
        protected System.Web.UI.WebControls.Image imgLithologySecondary;
        protected Telerik.Web.UI.RadComboBox radCboLithostratGroup;
        protected System.Web.UI.WebControls.Image imgLithostratGroup;
        protected Telerik.Web.UI.RadComboBox radCboLithostratFormation;
        protected System.Web.UI.WebControls.Image imgLithostratFormation;
        protected Telerik.Web.UI.RadComboBox radCboLithostratMember;
        protected System.Web.UI.WebControls.Image imgLithostratMember;
        protected System.Web.UI.WebControls.TextBox txtPermeability_Min;
        protected System.Web.UI.WebControls.TextBox txtPermeability_Max;
        protected System.Web.UI.WebControls.TextBox txtPorosityMin;
        protected System.Web.UI.WebControls.TextBox txtPorosityMax;
        protected System.Web.UI.WebControls.TextBox txtSandReservoir_Net_Gross_avg;
        protected System.Web.UI.WebControls.TextBox txtSandReservoir_Net_Gross_max;
        protected System.Web.UI.WebControls.TextBox txtSandReservoir_Net_Gross_min;
        protected System.Web.UI.WebControls.TextBox txtWaterSaturation_max;
        protected System.Web.UI.WebControls.TextBox txtGasInitiallyInPlace;
        protected System.Web.UI.WebControls.Image imgGasInitiallyInPlace;
        protected System.Web.UI.WebControls.TextBox txtStockTankOilInitially;
        protected System.Web.UI.WebControls.Image imgStockTankOilInitially;
        protected Telerik.Web.UI.RadComboBox radCboProductionStatus;
        protected System.Web.UI.WebControls.Image imgProductionStatus;
        protected System.Web.UI.WebControls.TextBox txtRecoveryFactorOil;
        protected System.Web.UI.WebControls.TextBox txtRecoveryFactorGas;
        protected System.Web.UI.WebControls.TextBox txtRecoverableOil;
        protected System.Web.UI.WebControls.TextBox txtRecoverableGas;
        protected System.Web.UI.WebControls.DropDownList cboDriveMechanism;
        protected System.Web.UI.WebControls.Image imgDriveMechanism;
        protected System.Web.UI.WebControls.DropDownList cboHydrocarbonMain;
        protected System.Web.UI.WebControls.Image imgHydrocarbonMain;
        protected System.Web.UI.WebControls.DropDownList cboHydrocarbonSecondary;
        protected System.Web.UI.WebControls.Image imgHydrocarbonSecondary;
        protected System.Web.UI.WebControls.TextBox txtOilViscosity;
        protected System.Web.UI.WebControls.Image imgOilViscosity;
        protected System.Web.UI.WebControls.TextBox txtPressureReservoirInitial;
        protected System.Web.UI.WebControls.Image imgPressureReservoirInitial;
        protected System.Web.UI.WebControls.TextBox txtOilGravity;
        protected System.Web.UI.WebControls.Image imgOilGravity;
        protected System.Web.UI.WebControls.TextBox txtSaveSearch;
        protected System.Web.UI.WebControls.Image imgSearchName;
        protected System.Web.UI.WebControls.CheckBox chbShared;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdSaveSearch;
        protected System.Web.UI.WebControls.Button cmdSearch;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdReset;
        protected System.Web.UI.WebControls.HiddenField hidDepositionalColumn;
        protected System.Web.UI.WebControls.HiddenField hidDepositionalValue;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidWordContent;
    }
}
