//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class RolesAndProfiles {
        protected System.Web.UI.HtmlControls.HtmlTableRow trRole;
        protected System.Web.UI.WebControls.DropDownList ddlRole;
        protected System.Web.UI.HtmlControls.HtmlTableRow trProfileType;
        protected System.Web.UI.WebControls.DropDownList ddlProfileType;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAssetType;
        protected System.Web.UI.WebControls.DropDownList ddlAssetType;
        protected System.Web.UI.HtmlControls.HtmlTableRow trResultType;
        protected System.Web.UI.WebControls.DropDownList ddlSearchNames;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAddRemoveItemsHeader;
        protected Telerik.Web.UI.RadListBox radLstBxSource;
        protected Telerik.Web.UI.RadListBox radLstBxDestination;
        protected Telerik.Web.UI.RadListBox radLstBxCategory;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAddRemoveItemsButton;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.ImageButton btnDeleteProfile;
        protected System.Web.UI.UpdatePanel updatePanelRolesProfiles;
        protected System.Web.UI.HtmlControls.HtmlTableRow trCategory;
        protected System.Web.UI.HtmlControls.HtmlTableRow trAddRemoveItems;
    }
}
