//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class SignificantWellEvents {
        protected System.Web.UI.WebControls.Panel Panel1;
        protected System.Web.UI.HtmlControls.HtmlTableCell tdDDLAssets;
        protected System.Web.UI.WebControls.CheckBox cboEventGroup;
        protected System.Web.UI.WebControls.DropDownList cblEventsGroup;
        protected System.Web.UI.WebControls.CheckBox cboCreatedBy;
        protected System.Web.UI.WebControls.TextBox txtCREATEDBY;
        protected System.Web.UI.WebControls.CheckBox cboEventType;
        protected System.Web.UI.WebControls.DropDownList cblEventsType;
        protected System.Web.UI.WebControls.CheckBox cboUpdatedBy;
        protected System.Web.UI.WebControls.TextBox txtUPDATEDBY;
        protected System.Web.UI.WebControls.CheckBox cboEventPriority;
        protected System.Web.UI.WebControls.CheckBox chbHigh;
        protected System.Web.UI.WebControls.CheckBox chbMedium;
        protected System.Web.UI.WebControls.CheckBox chbLow;
        protected System.Web.UI.WebControls.CheckBox cboOwnedBy;
        protected System.Web.UI.WebControls.TextBox txtOWNEDBY;
        protected System.Web.UI.WebControls.Button btnFilter;
        protected System.Web.UI.WebControls.Label lblErrorMessage;
        protected System.Web.UI.WebControls.HiddenField hdnSwedUrl;
    }
}
