//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class TVDepthPopup {
        protected System.Web.UI.WebControls.TextBox txtTVTopDepth;
        protected System.Web.UI.WebControls.TextBox txtTVBottomDepth;
        protected System.Web.UI.WebControls.TextBox txtTVDepthInterval;
        protected System.Web.UI.WebControls.Button btnPopulateDepth;
    }
}
