//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class UserPreferencesUI {
        protected System.Web.UI.WebControls.Panel UserPreferencesPanel;
        protected System.Web.UI.WebControls.Panel ExceptionPanel;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.DropDownList cboDisplay;
        protected System.Web.UI.WebControls.DropDownList cboDepthUnits;
        protected System.Web.UI.WebControls.DropDownList cboPressureUnits;
        protected System.Web.UI.WebControls.DropDownList cboTemperatureUnits;
        protected System.Web.UI.WebControls.DropDownList cboCountry;
        protected System.Web.UI.WebControls.DropDownList cboAsset;
        protected System.Web.UI.WebControls.DropDownList cboRecordsPerPage;
        protected System.Web.UI.WebControls.DropDownList cboBasin;
        protected System.Web.UI.WebControls.TextBox txtLinkTitle1;
        protected System.Web.UI.WebControls.TextBox txtLinkUrl1;
        protected System.Web.UI.WebControls.TextBox txtLinkTitle2;
        protected System.Web.UI.WebControls.TextBox txtLinkUrl2;
        protected System.Web.UI.WebControls.TextBox txtLinkTitle3;
        protected System.Web.UI.WebControls.TextBox txtLinkUrl3;
        protected System.Web.UI.WebControls.TextBox txtLinkTitle4;
        protected System.Web.UI.WebControls.TextBox txtLinkUrl4;
        protected System.Web.UI.WebControls.Button cmdSubmit;
        protected System.Web.UI.WebControls.Button cmdReset;
    }
}
