//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SharePoint.DREAM.Site.UI.UserControls {
    
    public partial class WellAdvSearch {
        protected System.Web.UI.WebControls.Panel ExceptionBlock;
        protected System.Web.UI.WebControls.Label lblSOAPException;
        protected System.Web.UI.WebControls.Label lblMessage;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidTest;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidSearchName;
        protected System.Web.UI.WebControls.Panel AdvancedSearchContent;
        protected System.Web.UI.WebControls.Panel GeneralExceptionBlock;
        protected System.Web.UI.WebControls.Label lblException;
        protected System.Web.UI.WebControls.DropDownList cboSavedSearch;
        protected System.Web.UI.WebControls.Image imgSavedSearch;
        protected System.Web.UI.WebControls.Button cmdTopSearch;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdTopReset;
        protected System.Web.UI.WebControls.DropDownList cboSearchCriteria;
        protected System.Web.UI.HtmlControls.HtmlInputFile fileUploader;
        protected System.Web.UI.WebControls.Label lblUniqueIdentifier;
        protected System.Web.UI.WebControls.TextBox txtUnique_Well_Identifier;
        protected System.Web.UI.WebControls.Image imgUWI;
        protected System.Web.UI.WebControls.Label lblWellName;
        protected System.Web.UI.WebControls.TextBox txtWell_Name;
        protected System.Web.UI.WebControls.Image imgWellName;
        protected System.Web.UI.WebControls.Label lblCommonName;
        protected System.Web.UI.WebControls.TextBox txtCommon_Name;
        protected System.Web.UI.WebControls.Image imgCommonName;
        protected System.Web.UI.WebControls.Label lblAliasName;
        protected System.Web.UI.WebControls.TextBox txtAlias_Name;
        protected System.Web.UI.WebControls.Image imgAliasName;
        protected System.Web.UI.WebControls.ListBox lstBasin;
        protected System.Web.UI.WebControls.Image imgBasin;
        protected System.Web.UI.WebControls.DropDownList lstCountry;
        protected System.Web.UI.WebControls.Image imgCountry;
        protected System.Web.UI.WebControls.Label lblCountryInfo;
        protected System.Web.UI.WebControls.CheckBox chbState;
        protected System.Web.UI.WebControls.ListBox lstState_Or_Province;
        protected System.Web.UI.WebControls.Image imgStateOrProvince;
        protected System.Web.UI.WebControls.Label lblStateInfo;
        protected System.Web.UI.WebControls.Label lblStateMessage;
        protected System.Web.UI.WebControls.CheckBox chbCounty;
        protected System.Web.UI.WebControls.ListBox lstCounty;
        protected System.Web.UI.WebControls.Image imgCounty;
        protected System.Web.UI.WebControls.Label lblCountyMessage;
        protected System.Web.UI.WebControls.CheckBox chbField_Identifier;
        protected System.Web.UI.WebControls.ListBox lstField_Identifier;
        protected System.Web.UI.WebControls.Image imgFieldName;
        protected System.Web.UI.WebControls.Label lblField_Identifier;
        protected System.Web.UI.WebControls.ListBox lstOnshore_Or_Offshore;
        protected System.Web.UI.WebControls.Image imgOnshoreOrOffshore;
        protected System.Web.UI.WebControls.ListBox lstKind;
        protected System.Web.UI.WebControls.Image imgWellType;
        protected System.Web.UI.WebControls.CheckBox chbFormation;
        protected System.Web.UI.WebControls.ListBox lstPick;
        protected System.Web.UI.WebControls.Image imgFormation;
        protected System.Web.UI.WebControls.Label lblFormation;
        protected System.Web.UI.WebControls.TextBox txtCurrent_Operator;
        protected System.Web.UI.WebControls.Image imgOperator;
        protected System.Web.UI.WebControls.ListBox lstCurrent_Status;
        protected System.Web.UI.WebControls.Image imgWellStatus;
        protected System.Web.UI.WebControls.RadioButtonList rdoRbDate;
        protected System.Web.UI.WebControls.TextBox txtFrom;
        protected System.Web.UI.WebControls.TextBox txtTo;
        protected System.Web.UI.WebControls.CheckBox chbGeographicalSearch;
        protected System.Web.UI.WebControls.RadioButton rdoLatLong;
        protected System.Web.UI.WebControls.RadioButtonList rdoRbLatLon;
        protected System.Web.UI.WebControls.TextBox txtMinLatDeg;
        protected System.Web.UI.WebControls.TextBox txtMinLatMin;
        protected System.Web.UI.WebControls.TextBox txtMinLatSec;
        protected System.Web.UI.WebControls.TextBox txtMinLatNS;
        protected System.Web.UI.WebControls.TextBox txtMinLonDeg;
        protected System.Web.UI.WebControls.TextBox txtMinLonMin;
        protected System.Web.UI.WebControls.TextBox txtMinLonSec;
        protected System.Web.UI.WebControls.TextBox txtMinLonEW;
        protected System.Web.UI.WebControls.TextBox txtMaxLatDeg;
        protected System.Web.UI.WebControls.TextBox txtMaxLatMin;
        protected System.Web.UI.WebControls.TextBox txtMaxLatSec;
        protected System.Web.UI.WebControls.TextBox txtMaxLatNS;
        protected System.Web.UI.WebControls.TextBox txtMaxLonDeg;
        protected System.Web.UI.WebControls.TextBox txtMaxLonMin;
        protected System.Web.UI.WebControls.TextBox txtMaxLonSec;
        protected System.Web.UI.WebControls.TextBox txtMaxLonEW;
        protected System.Web.UI.WebControls.TextBox txtSaveSearch;
        protected System.Web.UI.WebControls.Image imgSearchName;
        protected System.Web.UI.WebControls.CheckBox chbShared;
        protected System.Web.UI.WebControls.Button cmdSaveSearch;
        protected System.Web.UI.WebControls.Button cmdSearch;
        protected System.Web.UI.HtmlControls.HtmlInputButton cmdReset;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidWordContent;
    }
}
